// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	domain "main/src/domain"

	mock "github.com/stretchr/testify/mock"
)

// PetRepository is an autogenerated mock type for the PetRepository type
type PetRepository struct {
	mock.Mock
}

// GetAllPets provides a mock function with given fields:
func (_m *PetRepository) GetAllPets() ([]domain.PetResponse, error) {
	ret := _m.Called()

	var r0 []domain.PetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.PetResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.PetResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPetRepository creates a new instance of PetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PetRepository {
	mock := &PetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
